/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.vkutuev.dbsandbox

import me.vkutuev.dbsandbox.city.City
import me.vkutuev.dbsandbox.city.Cities
import me.vkutuev.dbsandbox.user.User
import me.vkutuev.dbsandbox.user.Users
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.StdOutSqlLogger
import org.jetbrains.exposed.sql.addLogger
import org.jetbrains.exposed.sql.transactions.transaction

private const val dbPath = "exposed_database.db"

fun main() {
    Database.connect("jdbc:sqlite:$dbPath", driver = "org.sqlite.JDBC")
    transaction {
        addLogger(StdOutSqlLogger)
        SchemaUtils.create(Users)
        SchemaUtils.create(Cities)

        User.new {
            name = "Vova"
            phone = 987654
        }
        User.new {
            name = "Ann"
            phone = 630474
            city = City.new {
                name = "Rybinsk"
            }
        }

        User.all().forEach { user -> println(user) }
    }
}
